export const DummyMovies = [
  {
    id: 1,
    title: "Lucifer",
    iframeLink: "https://www.youtube.com/embed/vXb1UBYRCAk",
    description: "watch on fmovies, goojara",
    category: "animation, anime, horror, shows",
    trailer: "https://youtube.com",
    movieLink: "https:fmovies.com",
    comments: [
      {
        id: 1,
        username: "mikedoe",
        comment: "This was honestly the best scene in lucifer",
        createdAt: "3 mins Ago",
      },
      {
        id: 2,
        username: "anukavee",
        comment: "This show is honestly underated",
        createdAt: "8 mins Ago",
      },
      {
        id: 3,
        username: "anukavee",
        comment: "This show is honestly underated",
        createdAt: "8 mins Ago",
      },
    ],
    creator: "chris doe",
    createdAt: "3 mins ago",
  },
  {
    id: 2,
    title: "Vikings",
    iframeLink: "https://www.youtube.com/embed/mqCE3O_AX70",
    description: "watch on fmovies, goojara",
    category: "animation, anime, horror, shows",
    trailer: "https://youtube.com",
    movieLink: "https:fmovies.com",
    comments: [
      {
        id: 1,
        username: "mikedoe",
        comment: "This was honestly the best scene in lucifer",
        createdAt: "3 mins Ago",
      },
      {
        id: 2,
        username: "anukavee",
        comment: "This show is honestly underated",
        createdAt: "8 mins Ago",
      },
      {
        id: 2,
        username: "anukavee",
        comment: "This show is honestly underated",
        createdAt: "8 mins Ago",
      },
      {
        id: 2,
        username: "anukavee",
        comment: "This show is honestly underated",
        createdAt: "8 mins Ago",
      },
    ],
    creator: "lucydoe",
    createdAt: "4 mins ago",
  },
  {
    id: 3,
    title: "The Last Kingdom",
    iframeLink: "https://www.youtube.com/embed/nEfRSCNr-2Y",
    description: "watch on fmovies, goojara",
    category: "animation, anime, horror, shows",
    trailer: "https://youtube.com",
    movieLink: "https:fmovies.com",
    comments: [
      {
        id: 1,
        username: "mikedoe",
        comment: "This was honestly the best scene in lucifer",
        createdAt: "3 mins Ago",
      },
      {
        id: 2,
        username: "anukavee",
        comment: "This show is honestly underated",
        createdAt: "8 mins Ago",
      },
    ],
    creator: "chris doe",
    createdAt: "6 mins ago",
  },
  {
    id: 4,
    title: "Edge Of Tomorrow",
    iframeLink: "https://www.youtube.com/embed/yUmSVcttXnI",
    description: "watch on fmovies, goojara",
    category: "animation, anime, horror, shows",
    trailer: "https://youtube.com",
    movieLink: "https:fmovies.com",
    comments: [
      {
        id: 1,
        username: "mikedoe",
        comment: "This was honestly the best scene in lucifer",
        createdAt: "3 mins Ago",
      },
      {
        id: 2,
        username: "anukavee",
        comment: "This show is honestly underated",
        createdAt: "8 mins Ago",
      },
    ],
    creator: "chris doe",
    createdAt: "3 mins ago",
  },
  {
    id: 5,
    title: "Moana",
    iframeLink: "https://www.youtube.com/embed/AEq15X1zjEE",
    description: "watch on fmovies, goojara",
    category: "animation, anime, horror, shows",
    trailer: "https://youtube.com",
    movieLink: "https:fmovies.com",
    comments: [
      {
        id: 1,
        username: "mikedoe",
        comment: "This was honestly the best scene in lucifer",
        createdAt: "3 mins Ago",
      },
      {
        id: 2,
        username: "anukavee",
        comment: "This show is honestly underated",
        createdAt: "8 mins Ago",
      },
    ],
    creator: "chris doe",
    createdAt: "3 mins ago",
  },
  {
    id: 6,
    title: "Raya And The Last Dragon",
    iframeLink: "https://www.youtube.com/embed/1VIZ89FEjYI",
    description: "watch on fmovies, goojara",
    category: "animation, anime, horror, shows",
    trailer: "https://youtube.com",
    movieLink: "https:fmovies.com",
    comments: [
      {
        id: 1,
        username: "mikedoe",
        comment: "This was honestly the best scene in lucifer",
        createdAt: "3 mins Ago",
      },
      {
        id: 2,
        username: "anukavee",
        comment: "This show is honestly underated",
        createdAt: "8 mins Ago",
      },
    ],
    creator: "chris doe",
    createdAt: "3 mins ago",
  },
  {
    id: 7,
    title: "Prey",
    iframeLink: "https://www.youtube.com/embed/NQOcZfSy-4Y",
    description: "watch on fmovies, goojara",
    category: "animation, anime, horror, shows",
    trailer: "https://youtube.com",
    movieLink: "https:fmovies.com",
    comments: [
      {
        id: 1,
        username: "mikedoe",
        comment: "This was honestly the best scene in lucifer",
        createdAt: "3 mins Ago",
      },
      {
        id: 2,
        username: "anukavee",
        comment: "This show is honestly underated",
        createdAt: "8 mins Ago",
      },
    ],
    creator: "chris doe",
    createdAt: "3 mins ago",
  },
  {
    id: 8,
    title: "Transformers Rise Of The Beast",
    iframeLink: "https://www.youtube.com/embed/nBksxvFD7dw",
    description: "watch on fmovies, goojara",
    category: "animation, anime, horror, shows",
    trailer: "https://youtube.com",
    movieLink: "https:fmovies.com",
    comments: [
      {
        id: 1,
        username: "mikedoe",
        comment: "This was honestly the best scene in lucifer",
        createdAt: "3 mins Ago",
      },
      {
        id: 2,
        username: "anukavee",
        comment: "This show is honestly underated",
        createdAt: "8 mins Ago",
      },
    ],
    creator: "chris doe",
    createdAt: "3 mins ago",
  },
  {
    id: 9,
    title: "Shannara Chronicles",
    iframeLink: "https://www.youtube.com/embed/ftwV7MoLTGQ",
    description: "watch on fmovies, goojara",
    category: "animation, anime, horror, shows",
    trailer: "https://youtube.com",
    movieLink: "https:fmovies.com",
    comments: [
      {
        id: 1,
        username: "mikedoe",
        comment: "This was honestly the best scene in lucifer",
        createdAt: "3 mins Ago",
      },
      {
        id: 2,
        username: "anukavee",
        comment: "This show is honestly underated",
        createdAt: "8 mins Ago",
      },
    ],
    creator: "chris doe",
    createdAt: "3 mins ago",
  },
  {
    id: 10,
    title: "Vampire Diaries",
    iframeLink: "https://www.youtube.com/embed/SnpHCu0vr9w",
    description: "watch on fmovies, goojara",
    category: "animation, anime, horror, shows",
    trailer: "https://youtube.com",
    movieLink: "https:fmovies.com",
    comments: [
      {
        id: 1,
        username: "mikedoe",
        comment: "This was honestly the best scene in lucifer",
        createdAt: "3 mins Ago",
      },
      {
        id: 2,
        username: "anukavee",
        comment: "This show is honestly underated",
        createdAt: "8 mins Ago",
      },
    ],
    creator: "chris doe",
    createdAt: "3 mins ago",
  },
  {
    id: 11,
    title: "The originals",
    iframeLink: "https://www.youtube.com/embed/E3OZEu3Q6OM",
    description: "watch on fmovies, goojara",
    category: "animation, anime, horror, shows",
    trailer: "https://youtube.com",
    movieLink: "https:fmovies.com",
    comments: [
      {
        id: 1,
        username: "mikedoe",
        comment: "This was honestly the best scene in lucifer",
        createdAt: "3 mins Ago",
      },
      {
        id: 2,
        username: "anukavee",
        comment: "This show is honestly underated",
        createdAt: "8 mins Ago",
      },
    ],
    creator: "chris doe",
    createdAt: "3 mins ago",
  },
  {
    id: 12,
    title: "Fubar",
    iframeLink: "https://www.youtube.com/embed/E3OZEu3Q6OM",
    description: "watch on fmovies, goojara",
    category: "animation, anime, horror, shows",
    trailer: "https://youtube.com",
    movieLink: "https:fmovies.com",
    comments: [
      {
        id: 1,
        username: "mikedoe",
        comment: "This was honestly the best scene in lucifer",
        createdAt: "3 mins Ago",
      },
      {
        id: 2,
        username: "anukavee",
        comment: "This show is honestly underated",
        createdAt: "8 mins Ago",
      },
    ],
    creator: "chris doe",
    createdAt: "3 mins ago",
  },
  {
    id: 13,
    title: "The Blacklist",
    iframeLink: "https://www.youtube.com/embed/MmC1uHL0_9g",
    description: "watch on fmovies, goojara",
    category: "animation, anime, horror, shows",
    trailer: "https://youtube.com",
    movieLink: "https:fmovies.com",
    comments: [
      {
        id: 1,
        username: "mikedoe",
        comment: "This was honestly the best scene in lucifer",
        createdAt: "3 mins Ago",
      },
      {
        id: 2,
        username: "anukavee",
        comment: "This show is honestly underated",
        createdAt: "8 mins Ago",
      },
    ],
    creator: "chris doe",
    createdAt: "3 mins ago",
  },
  {
    id: 14,
    title: "Flushed Away",
    iframeLink: "https://www.youtube.com/embed/swPfeLdKesg",
    description: "watch on fmovies, goojara",
    category: "animation, anime, horror, shows",
    trailer: "https://youtube.com",
    movieLink: "https:fmovies.com",
    comments: [
      {
        id: 1,
        username: "mikedoe",
        comment: "This was honestly the best scene in lucifer",
        createdAt: "3 mins Ago",
      },
      {
        id: 2,
        username: "anukavee",
        comment: "This show is honestly underated",
        createdAt: "8 mins Ago",
      },
    ],
    creator: "chris doe",
    createdAt: "3 mins ago",
  },
  {
    id: 15,
    title: "Ratatouille",
    iframeLink: "https://www.youtube.com/embed/NvM3nMbyeM8",
    description: "watch on fmovies, goojara",
    category: "animation, anime, horror, shows",
    trailer: "https://youtube.com",
    movieLink: "https:fmovies.com",
    comments: [
      {
        id: 1,
        username: "mikedoe",
        comment: "This was honestly the best scene in lucifer",
        createdAt: "3 mins Ago",
      },
      {
        id: 2,
        username: "anukavee",
        comment: "This show is honestly underated",
        createdAt: "8 mins Ago",
      },
    ],
    creator: "chris doe",
    createdAt: "23 mins ago",
  },
];

export const SingleDummy = [
  {
    id: 15,
    title: "Ratatouille",
    iframeLink: "https://www.youtube.com/embed/NvM3nMbyeM8",
    description: "watch on fmovies, goojara",
    category: "animation, anime, horror, shows",
    trailer: "https://youtube.com",
    movieLink: "https:fmovies.com",
    comments: [
      {
        id: 1,
        username: "mikedoe",
        comment: "This was honestly the best scene in lucifer",
        createdAt: "3 mins Ago",
      },
      {
        id: 2,
        username: "anukavee",
        comment: "This show is honestly underated",
        createdAt: "8 mins Ago",
      },
    ],
    creator: "chris doe",
    createdAt: "23 mins ago",
  },
];
